# constants.py

# DIMENSIONS
WIDTH = 1300
HEIGHT = 650

MARGIN_LEFT = 10
MENU_WIDTH = 300

BACKGROUND_POS = (0,0)
# NB-INFOS
NB_TAMAGOTCHIS = 5
DAILY_CROQUETTES = 50
ENVIRONMENT_TEXT = ["Salon", "Salle à Manger", "Salle de Jeux"]
NB_ENVIRONNEMENT = 3

# COLORS
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
LIGHT_GREEN = (144, 238, 144)
LIGHT_BLUE = (173, 216, 230)
LIGHT_YELLOW = (255,255,224)
LIGHT_RED = (255, 160, 160)
SKY_BLUE = (135, 206, 250)
GREY = (128, 128, 128)
DARK_BLUE = (0,0,50)

# FONTS SIZE
FONT_SMALL = 18
FONT_MEDIUM = 34
FONT_BIG = 60
FONT_BIG_BIG = 90

# TAMAGOTCHIS ------------------------------
TAMAGOTCHIS = ["Bébé_Yoda", "Bob", "Larry", "Marcel", "Patrick"]
TAMAGOTCHI_WIDTH = 210
TAMAGOTCHI_HEIGHT = 180
TAMAGOTCHI_MARGIN_LEFT = 160
TAMAGOTCHI_MARGIN_TOP = 340

TAMAGOTCHI_SPACE = 40
NAME_MARGIN_TOP = -78
NAME_MARGIN_LEFT = 20

# STATS BARRES 
STATS = ["Food", "Health", "Enthusiasm", "Energy"]
BARRE_COLORS = {"health" : RED, "food" : GREEN, "enthusiasm" : BLUE, "energy" : YELLOW}

STAT_WIDTH = 90
STAT_HEIGHT = 12
STAT_OFFSET_X = 95
STAT_OFFSET_Y = -55

STAT_SPACE = 13

# STATUS 
STATUS_SIZE = 40
STATUS_MARGIN_TOP = -48
STATUS_MARGIN_LEFT = 24
STATUT_SPACE = 10
# Initials
REST_DURATION = 10
INITIAL_FOOD = 200
INITIAL_HEALTH = 200
INITIAL_ENTHUSIASM = 200
INITIAL_ENERGY = 200

# Warnings
WARNING_FOOD = 20
WARNING_HEALTH = 20
WARNING_ENTHUSIASM = 20
WARNING_ENERGY = 50

# Gains
GAIN_FOOD_CROQUETTE = 50
GAIN_ENTHUSIASM_PLAY = 50
GAIN_ENERGY_SLEEP = 1
GAIN_HEALTH_SLEEP = 1

# Reduces
REDUCE_FOOD_WAKE = 5
REDUCE_HEALTH_WAKE = 1
REDUCE_HEALTH_FIGHT = 5
REDUCE_ENTHUSIASM_WAKE = 3
REDUCE_ENTHUSIASM_SLEEP = 1
REDUCE_ENERGY_PLAY = 50

# SLEEP DURATION
DAY_DURATION = 180  
MIN_SLEEP_DURATION = 30
MAX_SLEEP_DURATION = 60

# LABELS --------------------
COIN_LABEL_X = WIDTH - 270
COIN_LABEL_Y = 25

CROQUETTES_LABEL_X = 100
CROQUETTES_LABEL_Y = HEIGHT - 75

# SHOP --------------------- 
SHOP_ITEMS_HEIGHT = 70
SHOP_ITEMS_WIDTH = 70
SHOP_ITEMS_X = 70
SHOP_ITEMS_Y = HEIGHT // 2
SHOP_CANAPE_PRICE = 50
SHOP_CROQUETTE_PRICE = 2
SHOP_ITEM_PRICE = [SHOP_CROQUETTE_PRICE,SHOP_CANAPE_PRICE]


# IMAGES ---------------------
IMAGE_TAMAGOTCHI_SIZE = 95

IMAGE_SMALL_WIDTH = 50
IMAGE_SMALL_HEIGHT = 50

IMAGE_MEDIUM_WIDTH = 100
IMAGE_MEDIUM_HEIGHT = 100


# BUTTONS --------------------------------------------
BUTTON_TEXTS = ["Manger", "Jouer", "Sieste"]
BUTTON_COLORS = [LIGHT_BLUE, LIGHT_GREEN, LIGHT_YELLOW]

BUTTON_MARGIN_LEFT = 114

BUTTON_WIDTH = 60
BUTTON_HEIGHT = 27
BUTTON_SPACING = 6

ENVIRONMENT_BUTTON_WIDTH = 100
ENVIRONMENT_BUTTON_HEIGHT = ENVIRONMENT_BUTTON_WIDTH // 2
ENVIRONMENT_BUTTON_Y = 20
ENVIRONMENT_BUTTON_X = 110
ENVIRONMENT_BUTTON_MARGIN_LEFT = 250
MENU_BUTTON_MARGIN_LEFT = 30
MENU_BUTTON_MARGIN_TOP = 120

# MINIGAME ---------------------------------
MINIGAME_WIDTH = 500
MINIGAME_HEIGHT = 300

MINIGAME_LABEL_Y = HEIGHT // 2 - MINIGAME_HEIGHT // 2
MINIGAME_BUTTON_Y_SPACE = 50

MINIGAME_BUTTON_WIDTH = 400
MINIGAME_BUTTON_HEIGHT = 50

MINIGAME_BUTTON_X = WIDTH // 2 - MINIGAME_BUTTON_WIDTH // 2
MINIGAME_BUTTON_Y = 380

RPC_ICON_SIZE = (50, 50)
BALL_SIZE = 20

BB_BALL_WAIT = 400
BB_PADDLE_WIDTH = 100
BB_PADDLE_HEIGHT = 20
BB_PADDLE_Y = HEIGHT - 50
BB_BALL_SPEED = 2.25
BB_NB_BALLS = 3
BB_NB_BRICK_X = 10
BB_NB_BRICK_Y = 5
BB_BRICK_WIDTH = 110
BB_BRICK_HEIGHT = 20
BB_BRICK_MARGIN = 120

